<?php
declare(strict_types=1);

// WorldCupQualification SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

WorldCupQualificationUtility::setRegistrar(function (WorldCupQualificationUtility $u): void {
    $u->clean = [WorldCupQualificationClean::class, 'call'];
    $u->done = [WorldCupQualificationDone::class, 'call'];
    $u->make_error = [WorldCupQualificationMakeError::class, 'call'];
    $u->feature_add = [WorldCupQualificationFeatureAdd::class, 'call'];
    $u->feature_hook = [WorldCupQualificationFeatureHook::class, 'call'];
    $u->feature_init = [WorldCupQualificationFeatureInit::class, 'call'];
    $u->fetcher = [WorldCupQualificationFetcher::class, 'call'];
    $u->make_fetch_def = [WorldCupQualificationMakeFetchDef::class, 'call'];
    $u->make_context = [WorldCupQualificationMakeContext::class, 'call'];
    $u->make_options = [WorldCupQualificationMakeOptions::class, 'call'];
    $u->make_request = [WorldCupQualificationMakeRequest::class, 'call'];
    $u->make_response = [WorldCupQualificationMakeResponse::class, 'call'];
    $u->make_result = [WorldCupQualificationMakeResult::class, 'call'];
    $u->make_point = [WorldCupQualificationMakePoint::class, 'call'];
    $u->make_spec = [WorldCupQualificationMakeSpec::class, 'call'];
    $u->make_url = [WorldCupQualificationMakeUrl::class, 'call'];
    $u->param = [WorldCupQualificationParam::class, 'call'];
    $u->prepare_auth = [WorldCupQualificationPrepareAuth::class, 'call'];
    $u->prepare_body = [WorldCupQualificationPrepareBody::class, 'call'];
    $u->prepare_headers = [WorldCupQualificationPrepareHeaders::class, 'call'];
    $u->prepare_method = [WorldCupQualificationPrepareMethod::class, 'call'];
    $u->prepare_params = [WorldCupQualificationPrepareParams::class, 'call'];
    $u->prepare_path = [WorldCupQualificationPreparePath::class, 'call'];
    $u->prepare_query = [WorldCupQualificationPrepareQuery::class, 'call'];
    $u->graphql_body = [WorldCupQualificationGraphql::class, 'body'];
    $u->graphql_errors = [WorldCupQualificationGraphql::class, 'errors'];
    $u->result_basic = [WorldCupQualificationResultBasic::class, 'call'];
    $u->result_body = [WorldCupQualificationResultBody::class, 'call'];
    $u->result_headers = [WorldCupQualificationResultHeaders::class, 'call'];
    $u->transform_request = [WorldCupQualificationTransformRequest::class, 'call'];
    $u->transform_response = [WorldCupQualificationTransformResponse::class, 'call'];
});
